---
- name: Get geo replication volume facts
  hosts: "{{ _gluster_server_hostgroup_name }}"
  gather_facts: false
  vars_files:
    - ../../vars/main.yml
  tasks:
    - name: End play when gluster georeplication is not required
      ansible.builtin.meta: end_play
      vars:
        _replicas: "{{ _gluster_server_slaves | default([]) }}"
      when: _replicas | length == 0

    - name: Set gluster replica volumes
      ansible.builtin.set_fact:
        _gluster_target_volumes: "{{ _volumes_overwritten | rejectattr('name', 'equalto', _meta_volume) }}"
      vars:
        _replica_member: "{{ _gluster_server_slaves | sort | first }}"
        _volumes: "{{ _gluster_volumes | sort(attribute='name') }}"
        _volume_names: "{{ _volumes | map(attribute='name') }}"
        _volume_format: "{{ _volume_names | map(_map_format, _replica_member + '::%s') }}"
        _volume_dict: "{{ _volume_format | map(_to_dict, 'replica_name') }}"
        _volumes_overwritten: "{{ _volumes | zip(_volume_dict) | map('combine') }}"
        _meta_volume: "{{ gluster_meta_volume.name }}"
