---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: gluster-${MOLECULE_SCENARIO_NAME}-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster
  - name: gluster-${MOLECULE_SCENARIO_NAME}-02
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster
  - name: gluster-${MOLECULE_SCENARIO_NAME}-03
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      allow_world_readable_tmpfiles: true
      callbacks_enabled: ansible.posix.profile_tasks
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    verify: ../common/verify.yml
    side_effect: ../common/install.yml
    destroy: ../common/destroy.yml
  inventory:
    group_vars:
      all:
        libvirt_platforms: "{{ molecule_yml.platforms }}"
        gluster_volumes:
          - name: test
            brick: /data/test
            mount: /mnt/test
            paths:
              - a
              - b
              - c
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - side_effect
