---
- name: Query installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Get gluster server installation status
  when: gluster_server_package_name in packages | bool
  block:
    - name: Query installed gluster server package version
      ansible.builtin.shell:
        cmd: "dpkg-query -W -f='${Version}' {{ gluster_server_package_name }}"
      changed_when: false
      register: gluster_server_package_query

    - name: Set installed gluster package version fact
      ansible.builtin.set_fact:
        gluster_package_version_installed: "{{ gluster_server_package_query.stdout }}"
        gluster_server_installed: true

- name: Get target gluster server package version
  when: not gluster_server_package_name in packages | bool
  block:
    - name: Query available gluster server package
      ansible.builtin.shell:
        cmd: "apt-cache madison {{ gluster_server_package_name }} | awk '{ print $3 }' | grep '^{{ _gluster_release }}' | sort -r | head -1"
      changed_when: false
      register: gluster_server_package_query

    - name: Set installed gluster package version fact
      ansible.builtin.set_fact:
        gluster_package_version_target: "{{ gluster_server_package_query.stdout }}"
        gluster_server_installed: false

- name: Install gluster server
  ansible.builtin.package:
    name: "{{ gluster_server_package_name }}"

- name: Query installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Manage gluster service
  ansible.builtin.service:
    name: "{{ gluster_service_name }}"
    state: "{{ 'restarted' if _installed else 'present' }}"
  vars:
    _gluster_package: "{{ packages[gluster_server_package_name] }}"
    _gluster_installed: "{{ gluster_server_installed | bool }}"
    _gluster_package_version: "{{ gluster_package_version_installed if _gluster_installed else gluster_package_version_target }}"
    _gluster_installed_target: "{{ _gluster_package | map(attribute='version') | first }}"
    _installed: "{{ _gluster_package_version != _gluster_installed_target | bool }}"
