---
- name: Import start playbook
  ansible.builtin.import_playbook: pokerops.gluster.start

- name: Verify gluster service
  hosts: gluster
  vars:
    gluster_service_name: "glusterd.service"
  tasks:
    - name: Collect service facts
      ansible.builtin.service_facts:

    - name: Debug gluster service status
      ansible.builtin.debug:
        msg: "{{ services[gluster_service_name] }}"

    - name: Verify service run status
      ansible.builtin.fail:
        msg: "gluster service is not running"
      when: services[gluster_service_name].state not in ["running"]
