---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: End play for offline hosts
  ansible.builtin.meta: end_host
  when: not gluster_service_name in services

- name: Query pool list
  pokerops.gluster.pool_list:
  register: _member_query
  changed_when: false

- name: End play when node is not member of cluster
  ansible.builtin.meta: end_host
  vars:
    _members_output: "{{ _member_query.results | default ([]) }}"
    _existing_members: "{{ _members_output | map('regex_replace', 'localhost', inventory_hostname) }}"
  when: not inventory_hostname in _existing_members

- name: Manage gluster service
  ansible.builtin.service:
    name: "{{ gluster_service_name }}"
    state: "{{ gluster_service_state | default('started') }}"

- name: Query peer status
  ansible.builtin.shell: gluster peer status | grep -i state
  args:
    chdir: "/usr/sbin/"
  vars:
    _output: "{{ _peer_query.stdout_lines | default([]) }}"
    _query: "{{ _output | select('match', '.*Connected.*') }}"
    _group: "{{ gluster_target_members }}"
  retries: "{{ _gluster_retries }}"
  delay: "{{ _gluster_delay }}"
  until: (_query | length) == ((_group | length) - 1)
  register: _peer_query
  changed_when: false
  tags: skip_ansible_lint

- name: Verify volume statuses
  ansible.builtin.shell: gluster volume info {{ _volume }} | grep -i status
  args:
    chdir: "/usr/sbin/"
  vars:
    _volume: "{{ item.name }}"
    _query: "{{ _member_query.stdout }}"
    _status: "Status: Started"
  retries: "{{ _gluster_retries }}"
  delay: "{{ _gluster_delay }}"
  until: _status is search(_query)
  register: _member_query
  changed_when: false
  loop_control:
    label: "{{ _volume }}"
  loop: "{{ _gluster_volumes }}"
  tags: skip_ansible_lint
