---
- name: Query cluster state
  hosts: "{{ gluster_hostgroup_name | default('gluster') }}"
  become: true
  vars:
    gluster_service_name: "glusterd.service"
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify gluster service status
      ansible.builtin.assert:
        that:
          - gluster_service_name in services
          - services[gluster_service_name].state | lower == 'running'

    - name: Query volume info
      ansible.builtin.shell: gluster volume info {{ _volume }} | grep -i status
      args:
        chdir: "/usr/sbin/"
      vars:
        _brick: "{{ item.brick }}"
        _volume: "{{ item.name }}"
        _query: "{{ _member_query.stdout }}"
        _status: "Status: Started"
      failed_when: not _status is search(_query)
      register: _member_query
      changed_when: false
      loop_control:
        label: "{{ _volume }}"
      loop: "{{ gluster_volumes }}"
