---
- name: Import install playbook
  ansible.builtin.import_playbook: pokerops.gluster.install
  vars:
    gluster_server_hostgroup_name: gluster_server_up

- name: Query cluster state
  hosts: gluster_server_up
  become: true
  tasks:
    - name: Manage tasks within virtualenv
      block:
        - name: Query pool list
          pokerops.gluster.pool_list:
          register: _member_query
          changed_when: false

        - name: Set target node membership fact
          ansible.builtin.set_fact:
            _gluster_members: "{{ _existing_members }}"
            _gluster_initial: "{{ groups['gluster_server'] }}"
            _gluster_scaleup: "{{ groups['gluster_server_up'] }}"
          vars:
            _members_output: "{{ _member_query.results | default([]) }}"
            _members: "{{ _members_output | map(attribute='hostname') }}"
            _existing_members: "{{ _members | map('regex_replace', 'localhost', inventory_hostname) }}"

        - name: Debug gluster members
          ansible.builtin.debug:
            msg: "Debug gluster members: [{{ _gluster_members | join(', ') }}]"

        - name: Debug gluster initial members
          ansible.builtin.debug:
            msg: "Debug gluster initial members: [{{ _gluster_initial | join(', ') }}]"

        - name: Debug gluster scaleup members
          ansible.builtin.debug:
            msg: "Debug gluster scaleup members: [{{ _gluster_scaleup | join(', ') }}]"

        - name: Verify gluster members
          ansible.builtin.assert:
            that:
              - (_gluster_initial | length) < (_gluster_scaleup | length)
              - (_gluster_members | length) == (_gluster_scaleup | length)
              - _gluster_members | difference(_gluster_scaleup) | length == 0
              - _gluster_scaleup | difference(_gluster_members) | length == 0

      rescue:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent

        - name: Exit playbook execution
          ansible.builtin.fail:

- name: Import verification playbook
  ansible.builtin.import_playbook: ../common/verify.yml
  vars:
    gluster_server_hostgroup_name: gluster_server_up
