---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: gluster-server-${MOLECULE_SCENARIO_NAME}-primary-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster_server
      - gluster_server_primary
  - name: gluster-server-${MOLECULE_SCENARIO_NAME}-primary-02
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster_server
      - gluster_server_primary
  - name: gluster-server-${MOLECULE_SCENARIO_NAME}-primary-03
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster_server
      - gluster_server_primary
  - name: gluster-server-${MOLECULE_SCENARIO_NAME}-secondary-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster_server
      - gluster_server_secondary
  - name: gluster-server-${MOLECULE_SCENARIO_NAME}-secondary-02
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster_server
      - gluster_server_secondary
  - name: gluster-server-${MOLECULE_SCENARIO_NAME}-secondary-03
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 4
    size: 30G
    groups:
      - gluster_server
      - gluster_server_secondary
  - name: gluster-client-${MOLECULE_SCENARIO_NAME}-01
    image: "${MOLECULE_KVM_IMAGE}"
    cpu: 1
    mem: 2
    size: 5G
    groups:
      - gluster_client
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      allow_world_readable_tmpfiles: true
      callbacks_enabled: ansible.posix.profile_tasks
  playbooks:
    create: ../common/create.yml
    prepare: ../common/prepare.yml
    converge: ../common/install.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
  inventory:
    group_vars:
      all:
        libvirt_platforms: "{{ molecule_yml.platforms }}"
        gluster_nolog: false
        gluster_volumes:
          - name: test
            brick: /data/test
            mount: /mnt/test
            paths:
              - a
              - b
              - c
        gluster_groupset: primary
      gluster_server_secondary:
        gluster_georeplica_manage: true
        gluster_groupset: secondary
verifier:
  name: ansible
scenario:
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - side_effect
