---
- name: Set gluster volume fact
  hosts: "all"
  gather_facts: false
  tasks:
    - name: Set volume facts
      ansible.builtin.set_fact:
        _gluster_volumes: "{{ _volumes_filter }}"
      vars:
        _volume_defaults:
          state: present
        _volumes: "{{ gluster_volumes | sort(attribute='name') }}"
        _volumes_num: "{{ _volumes | length }}"
        _volumes_default: "{{ [_volume_defaults] * _volumes_num | int }}"
        _volumes_overwritten: "{{ _volumes_default | zip(_volumes) | map('combine') }}"
        _volumes_filter: "{{ _volumes_overwritten | rejectattr('state', 'equalto', 'absent') }}"

- name: Query cluster state
  hosts: "{{ gluster_server_hostgroup | default('gluster_server') }}"
  become: true
  vars:
    gluster_service_name: "glusterd.service"
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify gluster service status
      ansible.builtin.assert:
        that:
          - gluster_service_name in services
          - services[gluster_service_name].state | lower == 'running'

    - name: Query pool list
      pokerops.gluster.pool_list:
      register: _member_query
      changed_when: false

    - name: Query peer status
      ansible.builtin.shell: gluster peer status | grep -i state
      args:
        chdir: "/usr/sbin/"
      register: _peer_query
      changed_when: false
      tags: skip_ansible_lint

    - name: Verify gluster node membership
      ansible.builtin.assert:
        that:
          - inventory_hostname in _existing_members
          - (_group | length) == (_existing_members | length)
      vars:
        _members_output: "{{ _member_query.results | default([]) }}"
        _existing_members: "{{ _members_output | map('regex_replace', 'localhost', inventory_hostname) }}"
        _master_group: "{{ gluster_masters | default('gluster_server_primary') }}"
        _masters: "{{ groups[_master_group] }}"
        _slave_group: "{{ gluster_slaves | default('gluster_server_secondary') }}"
        _slaves: "{{ groups[_slave_group] }}"
        _group_name: "{{ _master_group if inventory_hostname in _masters else _slave_group }}"
        _group: "{{ groups[_group_name] }}"

    - name: Verify gluster node status
      ansible.builtin.assert:
        that: _query | length == 0
      vars:
        _output: "{{ _peer_query.stdout_lines }}"
        _query: "{{ _output | reject('regex', 'Connected') }}"

    - name: Verify volume statuses
      ansible.builtin.shell: gluster volume info {{ _volume }} | grep -i status
      args:
        chdir: "/usr/sbin/"
      vars:
        _volume: "{{ item.name }}"
        _query: "{{ _member_query.stdout }}"
        _status: "Status: Started"
      failed_when: not _status is search(_query)
      register: _member_query
      changed_when: false
      loop_control:
        label: "{{ _volume }}"
      loop: "{{ gluster_volumes }}"
      tags: skip_ansible_lint

- name: Test gluster client connection
  hosts: "gluster_client"
  become: true
  vars:
    _log_file: "{{ gluster_log_file | default('test.log') }}"
    _gluster_server_prefix: "{{ gluster_server_prefix | default('gluster_server') }}"
    _gluster_name: "{{ _gluster_server_prefix }}_verify"
  tasks:
    - name: Verify gluster mount paths
      ansible.builtin.assert:
        that: _query | length == _defined_mounts | length
      vars:
        _defined_mounts: "{{ _gluster_volumes | map(attribute='mount') }}"
        _existing_mounts: "{{ ansible_mounts | map(attribute='mount') }}"
        _query: "{{ _defined_mounts | select('in', _existing_mounts) }}"

    - name: Test gluster client mount
      ansible.builtin.copy:
        content: "Test file content"
        dest: "{{ _mount }}/{{ _log_file }}"
      vars:
        _mount: "{{ item.mount }}"
        _group: "{{ gluster_client_hostgroup | default('gluster_client_primary') }}"
      loop_control:
        label: "{{ _mount }}"
      loop: "{{ gluster_volumes }}"
      delegate_to: "{{ groups[_group] | first }}"

- name: Test gluster file replication
  hosts: "gluster_server"
  become: true
  vars:
    _log_file: "{{ gluster_log_file | default('test.log') }}"
    _gluster_server_prefix: "{{ gluster_server_prefix | default('gluster_server') }}"
    _gluster_name: "{{ _gluster_server_prefix }}_verify"
  tasks:
    - name: Verify gluster geo-replication
      ansible.builtin.stat:
        path: "{{ _file }}"
      vars:
        _file: "{{ item.mount }}/{{ _log_file }}"
        _results: "{{ _gluster_paths.results | default([]) }}"
        _paths: "{{ _results | map(attribute='stat') }}"
        _query: "{{ _paths | rejectattr('exists') }}"
      delay: 5
      retries: 5
      until: _query | length == 0
      loop_control:
        label: "{{ _file }}"
      loop: "{{ gluster_volumes }}"
      register: _gluster_paths

    - name: Verify gluster mount paths
      ansible.builtin.assert:
        that: _query | length == _defined_mounts | length
      vars:
        _defined_mounts: "{{ _gluster_volumes | map(attribute='mount') }}"
        _existing_mounts: "{{ ansible_mounts | map(attribute='mount') }}"
        _query: "{{ _defined_mounts | select('in', _existing_mounts) }}"
