---
- name: Manage gluster clients
  hosts: "{{ _gluster_client_hostgroup_name }}"
  become: true
  any_errors_fatal: true
  vars:
    _gluster_groupset: "{{ gluster_groupset | default('cluster') }}"
    _gluster_prefix: "{{ gluster_prefix | default('gluster') }}"
    _gluster_name: "{{ _gluster_prefix }}_{{ _gluster_groupset }}"
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Install gluster client
      ansible.builtin.package:
        name: "{{ gluster_client_package_name }}"

    - name: Create gluster client paths
      ansible.builtin.file:
        path: "{{ item.mount }}"
        state: directory
        owner: "{{ _gluster_client_user }}"
        group: "{{ _gluster_client_group }}"
        mode: "{{ _gluster_client_mode }}"
      loop_control:
        label: "{{ item.mount }}"
      loop: "{{ _gluster_volumes }}"

    - name: Mount gluster source volume
      ansible.posix.mount:
        src: "{{ _server }}:/{{ item.name }}"
        path: "{{ item.mount }}"
        fstype: glusterfs
        opts: "{{ _options }}"
        state: mounted
      vars:
        _server: "{{ groups[_gluster_name] | first }}"
        _replica_manage: "{{ _gluster_georeplica_manage }}"
        _option_default: "{{ item.opts | default('defaults') }}"
        _options: "{{ 'ro' if _replica_manage else _option_default }}"
      loop_control:
        label: "{{ item.name }} - {{ item.mount }}"
      loop: "{{ _gluster_volumes }}"
