---
- name: Install gluster
  hosts: "{{ _gluster_hostgroup_name }}"
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Install gluster server
      ansible.builtin.package:
        name: "{{ gluster_package_name }}"

    - name: Manage gluster service
      ansible.builtin.systemd:
        name: "{{ gluster_service_name }}"
        state: started
        enabled: true
