---
- name: Run Gluster facts
  ansible.builtin.import_playbook: pokerops.gluster.facts

- name: Prepare Gluster nodes
  ansible.builtin.import_playbook: pokerops.gluster.prepare

- name: Deploy Gluster
  ansible.builtin.import_playbook: pokerops.gluster.gluster

- name: Run Gluster Geo Replication user
  ansible.builtin.import_playbook: pokerops.gluster.ssh
