---
- name: Run Gluster facts
  ansible.builtin.import_playbook: pokerops.gluster.facts

- name: Prepare Gluster nodes
  ansible.builtin.import_playbook: pokerops.gluster.prepare

- name: Deploy Gluster
  ansible.builtin.import_playbook: pokerops.gluster.gluster

- name: Run Gluster Geo Replication delete
  ansible.builtin.import_playbook: pokerops.gluster.georeplication.delete

- name: Remove Gluster Client mount points
  ansible.builtin.import_playbook: pokerops.gluster.client
  vars:
    _volumes: "{{ _gluster_volumes }}"
    _volumes_state: "{{ _volumes | selectattr('state', 'defined') }}"
    _gluster_client_volumes: "{{ _volumes_state | selectattr('state', 'equalto', 'absent') }}"
  when: _gluster_client_volumes | length > 0

- name: Deploy Gluster volumes
  ansible.builtin.import_playbook: pokerops.gluster.volumes

- name: Run Gluster Geo Replication user
  ansible.builtin.import_playbook: pokerops.gluster.georeplication.ssh

- name: Run Gluster Geo Replication sessions create
  ansible.builtin.import_playbook: pokerops.gluster.georeplication.create

- name: Deploy Gluster Clients
  ansible.builtin.import_playbook: pokerops.gluster.client
  vars:
    _gluster_client_volumes: "{{ _gluster_volumes }}"
