---
- name: Prepare gluster members
  hosts: "{{ _gluster_group_name }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: End play for offline hosts
      ansible.builtin.meta: end_host
      when:
        - gluster_service_name in services
        - services[gluster_service_name].state | lower != 'running'

    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"

    - name: Query node membership
      ansible.builtin.command:
        cmd: "gluster pool list"
      ignore_errors: true
      register: _member_query

    - name: Create brick paths
      ansible.builtin.file:
        path: "{{ item.brick }}"
        state: directory
      loop_control:
        label: "{{ item.brick }}"
      loop: "{{ _gluster_volumes }}"
