---
- name: Prepare gluster members
  hosts: "{{ _gluster_server_hostgroup_name }}:{{ _gluster_client_hostgroup_name }}"
  become: true
  vars_files:
    - ../vars/main.yml
  any_errors_fatal: true
  tasks:
    - name: Manage tasks within virtualenv
      block:
        - name: Add host entries for cluster members
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: ".*{{ item }}.*"
            line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
          vars:
            _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
            _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
            _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
          loop: "{{ groups[_gluster_server_hostgroup_name] }}"

        - name: Configure gluster repository
          ansible.builtin.include_role:
            name: pokerops.gluster.gluster_repo
          vars:
            gluster_repo_release: "{{ _gluster_release }}"

      rescue:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent

        - name: Exit playbook execution
          ansible.builtin.fail:
