---
- name: Run Gluster virtualenv
  ansible.builtin.import_playbook: pokerops.gluster.virtualenv

- name: Run Gluster facts
  ansible.builtin.import_playbook: pokerops.gluster.facts

- name: Restart gluster members
  hosts: "{{ _gluster_hostgroup_restart }}"
  become: true
  serial: 1
  vars:
    _gluster_hostgroup_restart: "{{ gluster_server_hostgroup_restart | default(_gluster_server_hostgroup_name) }}"
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Manage tasks within virtualenv
      block:
        - name: Include service tasks
          ansible.builtin.include_tasks: tasks/service.yml
          vars:
            gluster_service_state: restarted

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
