---
- name: Run Gluster facts
  ansible.builtin.import_playbook: pokerops.gluster.facts

- name: Start gluster members
  hosts: "{{ _gluster_server_hostgroup_name }}"
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Include service tasks
      ansible.builtin.include_tasks: tasks/service.yml
      vars:
        gluster_service_state: started
