---
- name: Run Gluster virtualenv
  ansible.builtin.import_playbook: pokerops.gluster.virtualenv

- name: Stop gluster members
  hosts: "{{ _gluster_server_hostgroup_name }}"
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Manage tasks within virtualenv
      block:
        - name: Gather service facts
          ansible.builtin.service_facts:

        - name: End play for offline hosts
          ansible.builtin.meta: end_host
          when: not gluster_service_name in services

        - name: Query pool list
          pokerops.gluster.pool_list:
          register: _member_query
          changed_when: false

        - name: End play when node is not member of cluster
          ansible.builtin.meta: end_host
          vars:
            _members_output: "{{ _member_query.results | default([]) }}"
            _members: "{{ _members_output | map(attribute='hostname') }}"
            _existing_members: "{{ _members | map('regex_replace', 'localhost', inventory_hostname) }}"
          when: not inventory_hostname in _existing_members

        - name: Stop gluster service
          ansible.builtin.service:
            name: "{{ gluster_service_name }}"
            state: stopped

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
