---
name: lint

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

defaults:
  run:
    working-directory: "pokerops.gluster"

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "pokerops.gluster"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: "pokerops.gluster"
          devbox-version: ${{ vars.DEVBOX_VERSION }}

      - name: Lint code
        run: devbox run -- make lint
